[package]
name = "betaflight-blackbox-splitter"
version = "0.1.0"
authors = ["Ilya Epifanov <elijah.epifanov@gmail.com>"]

[dependencies]
regex = "0.2.5"
clap = { version = "2.29.2", default-features = false, features = ["suggestions", "vec_map"] }
